Algoritmo "Exercício 1º "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Silvia Fiacador
// Descrição   : Exercício 1º
// Autor(a)    : Lucas Arifa
// Data atual  : 8/11/2020
Var
   numero1 : inteiro
Inicio

   escreva("Escolha um número: ")
   leia (numero1)
   se numero1%2 = 0 entao
      Escreval("O seu número é Par")
   senao faca
         Escreval("O seu número é Ímpar")
   fimse
Fimalgoritmo