Algoritmo "Primeira Aula - VisualG"

Var

nome  : caractere
idade : real
x     : real

Inicio

   escreva ("digite seu nome")
   leia (nome)
   escreva ("digite sua idade")
   leia (idade)
x <- (65 - idade)
se (idade < 18)entao
   escreva (nome)
   escreval (" voce ainda é muito novo")
senao entao
   escreva (nome)
   escreva (" faltam ")
   escreva (x)
   escreval (" anos para que vc se aposente")
fimse
Fimalgoritmo
