Algoritmo "ListaDeExercícios02"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Silvia Fiacador
// Descrição   :  Lista De Exercícios - algoritimo 1
// Autor(a)    :  Lucas Arifa
// Data atual  : 8/9/2020
Var
nome, sobrenome, nomeCompleto:caractere
Inicio

escreval("Qual seu nome ?")
leia(nome)
escreval("E seu sobrenome ?")
leia(sobrenome)
escreval("Obrigado!!")
nomeCompleto <- nome + sobrenome
escreval("Olá, Bem Vindo a equipe dois " + nomeCompleto + "!!")
Fimalgoritmo

