Algoritmo "exercício 8"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JS Barros
// Descrição   : Exercício 8
// Autor(a)    : Lucas Arifa
// Data atual  : 8/14/2020
Var
   picoleTipo1, picoleTipo2, picoleTipo3, continue, close :
Inicio

   escreval("     |        Compre picolé!      |          ")
   escreval("        |     Continuar:      |          ")
   escreval("        |     sim ou não?     |          ")
   escreval("        |                     |          ")
   leia(continue)
   se (continue = verdadeiro) entao faca
      escreval("        |     :      |          ")
      escreval("        |     Continuar:      |          ")
      escreval("        |     sim ou não?     |          ")
      escreval("        |     Continuar:      |          ")


   senao


   fimse



Fimalgoritmo