Algoritmo "Área do Triângulo"
// Disciplina  :[Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Exercício 3
// Autor(a)    : Luacs Arifa
// Data atual  : 8/13/2020
Var
num1 , num2, soma : inteiro

Inicio

Escreval("Escreva um número:")
leia(num1)
Escreval("Escreva outro número:")
leia(num2)

soma <- num1 + num2

escreval("A soma dos dois numeros é ", soma)

Fimalgoritmo